<?php


namespace Zl\Common\Subtask;


use Zl\Common\Constants\SubtaskStatus;
use Zl\Common\Constants\SubtaskType;
use Zl\Common\Models\Subtask as SubtaskModel;
use Zl\Common\Subtask\BaseSubtask\BaseTccSubtask;
use Zl\Common\Subtask\BaseSubtask\ProcessorSubtask;

class TccSubtask extends BaseTccSubtask
{
    public $serverType = 'TCC';
    public $type = SubtaskType::TCC;

    public function try()
    {
        return parent::_try(); // TODO: Change the autogenerated stub
    }
}