<?php


namespace Zl\Common\Subtask;


use Zl\Common\Constants\SubtaskType;
use Zl\Common\Subtask\BaseSubtask\BaseTccSubtask;

class XaSubtask extends BaseTccSubtask
{
    public $serverType = 'XA';
    public $type = SubtaskType::XA;

    public function prepare()
    {
        return parent::_try(); // TODO: Change the autogenerated stub
    }


}